### PR TITLE
Snapshot testing

### PR DESCRIPTION
**Pull request by halas**
I setup snapshot testing and added barebone logo component to check how it works. 
I changed configuration of storybook so that it looks for storeis in `src` directory. 
I think it makes much more sense to keep story and tests for component all in one place. 
What do yall think?

### CODE REVIEW

**Comment by halas** [comment]
Ok, I will have to figure out tomorrow how to update snapshots on CI servers

**Comment by halas** [comment]
ok, snapshots test pass, indeed I needed to include screenshots in repo. Tests fail now because of cypress.

**Comment by halas** [comment]
fine with me, let's not do them. I think aproach, let's test something and expand when we get errors that were not caught by current tests is fine

**Comment by halas** [comment]
what do you think about writing stories next to components, like I showcased with "logo" not in common stories file?

**Comment by rhoffmann** [comment]
I am ok with colocating tests with their respective components. For a general overview of the whole storybook system it might be easier starting in a central location, until we think it gets too messy. There will probably be certain story fragments that will address more than one component, which will make collocation difficult to decide. What’s you feeling about that?

**Comment by halas** [comment]
wouldn't they be wrapped in another component then?

**Comment by rhoffmann** [comment]
hm i was thinking about stories which show multiple components in action, also the stories code imports a lot of things from all over the place, i think if we put them down the source tree, we will be importing things very irregularly. i think putting them in a central location (the storybook) would be a more convenient solution. but lets not get ahead of ourselves and first create some stuff :)

**Comment by halas** [comment]
Ok, I close this PR then :) Will remove cypress in another.

**Pull request closed without merging**
